// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolApi.Data;

namespace SchoolApi.Data.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    partial class SchoolDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SchoolLibrary.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = "f83013ce-dcf4-4166-859c-15a5989a61fe",
                            FirstName = "Tom",
                            LastName = "Day",
                            School = "Physics"
                        },
                        new
                        {
                            StudentId = "e64f7478-0528-44e9-98d9-70f39a139fb7",
                            FirstName = "Ann",
                            LastName = "Fox",
                            School = "Geology"
                        },
                        new
                        {
                            StudentId = "21bb2bce-173c-44c3-9585-11946ceb1d6f",
                            FirstName = "Art",
                            LastName = "Ash",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = "d3e4e52b-83a7-4f61-893e-86844529cc8d",
                            FirstName = "Mia",
                            LastName = "Hay",
                            School = "Science"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
